---
version: '3.9'
services:
  db:
    image: postgres:12.11
    restart: always
    environment:
      POSTGRES_DB: feeds
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - streamrss:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app

  nats:
    image: nats:2.8-linux
    entrypoint: /nats-server
    command:
      - "--name"
      - "streamrss"
      - "--jetstream"
      - "--http_port"
      - "8222"
      - "--cluster_name"
      - "streamrss-cluster"
    restart: always
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    networks:
      - app

  api:
    build: ./
    restart: always
    ports:
      - 8000:8000
    networks:
      - app
    depends_on:
      - db

  worker:
    build: ./
    entrypoint: ./worker-entrypoint.sh
    restart: always
    networks:
      - app

networks:
  app:
    driver: bridge

volumes:
  streamrss:
